---
name: Cruises

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#37_8_*_*_3
    # weekly on Wednesday at 8:37 AM UTC
    - cron: 37 8 * * 3

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  BOT: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch cruises
        run: python -m in_port_today.cli cruises --month 0..1

      - uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83
        id: cpr
        with:
          commit-message: 🤖 Update cruise schedule
          author: ${{ env.BOT }}
          committer: ${{ env.BOT }}
          branch: cruises
          delete-branch: true
          title: 🤖 Update cruise schedule
          body: Created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          labels: auto

      - name: Auto merge pull request
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --squash --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ github.token }}
